#!/bin/bash
sudo -s
sudo yum update -y
sudo yum upgrade -y
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 16
npm install -g npm@9.6.7
npm install -g serve
npm install pm2 -g
pm2 stop all
cd /home/ec2-user/dashtar-backend
npm install
pm2 start npm --name "backend" -- run dev
pm2 serve /home/ec2-user/build 4000 --spa
echo Successfully connected





